import {exp} from 'react-native/Libraries/Animated/src/Easing';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_TRUE = 'LOGIN_TRUE';
export const LOGIN_FALSE = 'LOGIN_FALSE';

export const PAYMENT_INITIATE_LOADING = 'PAYMENT_INITIATE_LOADING';
export const PAYMENT_INITIATE_SUCCESS = 'PAYMENT_INITIATE_SUCCESS';
export const PAYMENT_INITIATE_FAIL = 'PAYMENT_INITIATE_FAIL';
export const PAYMENT_INITIATE_CLEAR = 'PAYMENT_INITIATE_CLEAR';

export const PAYMENT_VERIFY_LOADING = 'PAYMENT_VERIFY_LOADING';
export const PAYMENT_VERIFY_SUCCESS = 'PAYMENT_VERIFY_SUCCESS';
export const PAYMENT_VERIFY_FAIL = 'PAYMENT_VERIFY_FAIL';
export const PAYMENT_VERIFY_CLEAR = 'PAYMENT_VERIFY_CLEAR';

export const UPDATE_DEVICE_LOADING = 'UPDATE_DEVICE_LOADING';
export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';
export const UPDATE_DEVICE_FAIL = 'UPDATE_DEVICE_FAIL';

export const GET_NOTIFICATION_LOADING = 'GET_NOTIFICATION_LOADING';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAIL = 'GET_NOTIFICATION_FAIL';

export const PAYMENT_HISTORY_LOADING = 'PAYMENT_HISTORY_LOADING';
export const PAYMENT_HISTORY_SUCCESS = 'PAYMENT_HISTORY_SUCCESS';
export const PAYMENT_HISTORY_FAIL = 'PAYMENT_HISTORY_FAIL';

export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_CLEAR_AUTH = 'CHANGE_PASSWORD_CLEAR_AUTH';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
